\lab{Exceptions and File I/O}{Exceptions and File I/O Protocol}
\label{lab:Exceptions}

\objective{
Python uses \emph{Exceptions} to handle errors.
Understanding and utilizing the exception class hierarchy is an important skill for regulating program usage and informing the programmer of problems.
Python also has a powerful file object that allows data to be read in from and out to files easily.
Understanding how this object's class attributes and methods is essential to data manipulation and analysis.
In this final introductory lab, we explore exceptions and file I/O protocol from the view of Object Oriented Programming.}

% TODO
%       - print statments --> print function calls in Python 3 (parentheses)
%       - String Formatting section. ALMOST THERE!!!!
%       - Additional material section?

% EXCEPTIONS ==================================================================

\section*{Exceptions}

Every programming language has a formal way of indicating and handling errors.
In Python, we raise and handle \emph{Exceptions}.
There are different kinds of exceptions, each with its appropriate usage and meaning\footnote{See \url{https://docs.python.org/2/library/exceptions.html} for the complete list of Python's built-in exception classes.}.

\begin{lstlisting}
# A 'NameError' exception indicates that a nonexistant name was used.
>>> print(x)
<<Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined>>

# An 'AttributeError' exception indicates that a nonexistant method
# or attribute was called on some object.
>>> [1, 2, 3].fly()
<<Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'fly'>>

# A 'SyntaxError' exception indicates bad Python syntax.
>>> def myFunction(a, b)             # forgot the colon!
<<  File "<stdin>", line 1
    def myFunction(a, b)
                       ^
SyntaxError: invalid syntax>>
\end{lstlisting}

\subsection*{Raising Exceptions}

Many exceptions, like the ones demonstrated above, are due to coding mistakes and typos.
Exceptions can also be used programmatically and intentionally to indicate a problem to the user or programmer.
To raise an exception, use the keyword \li{raise}, followed by the name of the exception class.
As soon as an exception is raised, the program stops running unless the exception is handled properly.

Exception objects can be initialized with any number of arguments.
These arguments are stored in the exception object as a class attribute called \li{args}, and also serve as the string representation of the object.
Most commonly, we provide a simple message with information about the error.

\begin{lstlisting}
# Raise a generic exception, without an error message.
>>> if 7 is not 7.0:
...     raise Exception
... 
<<Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception>>

# Now raise a more specific exception, with an error message included.
>>> for x in range(10):
...     if x > 5:
...         raise ValueError("'x' should not exceed 5.")
...     print(x),
... 
0 1 2 3 4 5
<<Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: 'x' should not exceed 5.>>
\end{lstlisting}

% Problem 1: Raising Exceptions 101
% Note that this my_func already raises TypeErrors, but the students' messages should be more informative than what pops up on the interpreter.
\begin{problem}
Python functions do not require specific types for each parameter.
Sometimes, however, it is important to validate functional inputs before they are utilized.
Consider the following function.
\begin{lstlisting}
def my_func(a, b, c, d, e):
    print("The first argument is " + a)
    x = sum([b, c])
    y = d + e
    return a, x, y
\end{lstlisting}
Modify \li{my_func()} so that it raises a \li{TypeError} if:
\begin{enumerate}
\item $a$ is not a string (of type \li{str}),
\item $b$ or $c$ is not a numerical type (\li{int}, \li{float}, \li{long}, or \li{complex}), or
\item $d$ and $e$ are not the same type.
\end{enumerate}
Include an informative error message with each exception.

(Hint: investigate the \li{type} and \li{isinstance} built-in functions.)
\end{problem}

\subsection*{Handling Exceptions}

To prevent an exception from stopping the program, it must be handled by
putting the problematic lines of code in a \li{try} block.
An \li{except} block then follows.
If an exception is thrown, the compiler exits the \li{try} block and enters the \li{except} block.

\begin{lstlisting}
# the 'try' block should hold any lines of code that might raise an exception.
>>> try:
...     raise Exception("for no reason.")
...     print("No exception raised")
... # the 'except' block is entered into when an exception is raised.
... except:
...     print("Exception raised!")
... # The program then continues as usual.
... print("Got to the end.")
... 
Exception raised!
Got to the end.
\end{lstlisting}

Exceptions can be caught generally or by class.
Having \li{except} by itself will catch \emph{any} exception raised in the \li{try} block, but this approach is very broad and is typically considered bad coding practice.
Instead, be specific about the kind (or kinds) of exceptions you expect to encounter.

Additionally, an exception that is caught by an \li{except} statement can be captured as a variable within the \li{except} block if it is declared using the keyword \li{as}.

\begin{lstlisting}
# Catch only a specific class of exceptions.
>>> try:
...     bad = 100 / 0
... except ZeroDivisionError as e:
...     print(e)
... 
<<integer division or modulo by zero>>

# Here a different exception is raised than the one in the except statement.
>>> try:
...     1 + 'a' + 2 + 'b' + 3
... except ValueError as e:
...     print(e)
<<Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'>>

>>> try:
...     import magic
... except ImportError as e:
...     print "Sorry!", e
... 
Sorry! No module named magic
\end{lstlisting}

Multiple kinds of exceptions can be caught by a single \li{except} statement using a parenthesized list of exceptions.
There can also be more than one \li{except} statements corresponding to a single \li{try} statement, each indicating which exception class(es) to catch.
An \li{else} statement can also be attached after \li{except} statements, which is only executed if the \li{try} block is executed to completion.

Trace through the following examples carefully.
Understanding this control flow is vital to being able to use exceptions effectively.

\begin{lstlisting}
# Catch two kinds of exceptions in the same except statement.
>>> try:
...     print "Started in the try block."
...     raise ValueError("This is a ValueError!")
...     print "Got the the end of the try block."
... except (ValueError, TypeError, ArithmeticError) as e:
...     print "An exception was raised:", e
...
<<Started in the try block.
An exception was raised: This is a ValueError!>>

# Equivalently, catch each kind of exception with a separate except statement.
>>> try:
...     print "Started in the try block."
...     raise TypeError("This is a TypeError!")
... except ValueError as e:
...     print "Bad value:", e
... except TypeError as e:
...     print "Bad type:", e
... except ArithmeticError as e:
...     print "Bad math:", e
...
<<Started in the try block.
Bad type: This is a TypeError!>>

# The 'else' block is executed if no exceptions are raised.
>>> try:
...     print "Started in the try block."
... except (ValueError, TypeError, ArithmeticError) as e:
...     print "An exception was raised:", e
... else:
...     print "No exceptions were raised."
...
<<Started in the try block.
No exceptions were raised.>>

# Note that the else statement does not catch any exceptions.
>>> try:
...     print "Started in the try block."
...     raise ValueError("This is a ValueError!")
... except (TypeError, ArithmeticError) as e:
...     print "An exception was raised:", e
... else:
...     print "No exceptions were raised."
...
<<Started in the try block.
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: This is a ValueError!>>
\end{lstlisting}

More examples of raising and handling exceptions can be found at \url{https://docs.python.org/2/tutorial/errors.html}.

% Catch a KeyboardInterrupt.
% This example is very simple; it could be expanded to a simple random walk.
\begin{problem}
A \li{KeyboardInterrupt} is a special exception that can be triggered at any time by entering \li{ctrl c} (on most systems) in the keyboard.
Usually a \li{KeyboardInterrupt} is used to manually escape faulty code that runs forever, but it can also be used intentionally to truncate a process.

Consider the following function.

\begin{lstlisting}
def forever(max_iters=1000000000):
    iters = 0
    while True:
        iters += 1
        if iters >= max_iters:
            break
    print "Process Completed."
    return iters
\end{lstlisting}
Modify \li{forever()} so that if the user raises a \li{KeyboardInterrupt} before \li{iters} reaches \li{max_iters}, the function prints ``Process Interrupted'' and returns the current value of \li{iters}.
If no \li{KeyboardInterrupt} is raised, the function should still print ``Process Completed'' and return \li{iters} as before.
\end{problem}

% TODO: For Python 3, discuss chaining Exceptions.
\begin{comment}
\subsection*{Chaining Exceptions}
\begin{lstlisting}
>>> try:
>>>     raise ValueError("First Exception")
>>> except ValueError as e:
>>>     raise ZeroDivisionError("Second Exception") from e
\end{lstlisting}
\end{comment}

\subsection*{The Exception Hierarchy}

The built-in Python exceptions are organized into a class hierarchy.
This can lead to some confusing behavior if one is not aware of the relationships between exception classes.
Consider the following example:

\begin{lstlisting}
# In this example, the exception is caught.
>>> try:
...     raise ValueError("This is a ValueError!")
... except StandardError as e:
...     print e
... print "Process finished."
...
<<This is a ValueError!
Process finished.>>

# But in this case, the exception is not caught.
>>> try:
...     raise StandardError("This is a StandardError!")
... except ValueError as e:
...     print e
... print "Process finished."
...
<<Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
StandardError: This is a StandardError!>>
\end{lstlisting}

Why was the first error caught, but not the second?
It turns out that the \li{ValueError} class inherits from the \li{StandardError}.
Thus a \li{ValueError} \emph{is} a \li{StandardError}, so the first \li{except} statement was able to catch the exception, but a \li{StandardError} is \emph{not} a \li{ValueError}, so the second \li{except} statement could not catch the exception.

See \url{https://docs.python.org/2/library/exceptions.html#exception-hierarchy} for the complete hierarchy of built-in exception classes.

\subsection*{Custom Exceptions}

Custom exceptions can be defined by writing a class that inherits from some existing exception class.
The generic \li{Exception} class is typically the parent class of choice.

% Problem 3: Create a custom exception class.
\begin{problem}
Create a class called \li{InvalidOptionError} that inherits from the built-in \li{Exception} class.
This class should behave exactly like \li{Exception}, without any additional methods or attributes.

(Hint: the entire class definition can be done in two short lines.)
\end{problem}

% FILE I/O ====================================================================

\section*{File Input and Output in Python}

Python has a useful \li{file} object which acts as an interface to all kinds of different file streams.
The built-in function \li{open} creates a \li{file} object.

\begin{lstlisting}
>>> myfile = open('in.txt', 'r')        # Open 'in.txt' with read-only access.
>>> for line in myfile:                 # Print out each line of the file.
...     print line
...
>>> myfile.close()                      # Close the file connection.
\end{lstlisting}

The \li{open} command accepts up to three arguments: the filename, mode, and buffering options.
The mode determines the kind of access to use when opening the file.
Possible mode strings are:
\begin{description}
\item \li{'r'}: opens a file for read-only access.
This is the default mode.
\item \li{'w'}: opens a file for write-only access.
This mode creates the file if it doesn't already exist, and \textbf{overwrites everything} in the file if it does exist.
\item \li{'a'}: opens a file for appending.
This mode is like write-only, but instead of overwriting existing data any new data is appended to the end of the file.
This mode also creates a new file if it doesn't already exist.
\end{description}

\subsection*{The With Statement}

If a file cannot be opened for any reason, an \li{IOException} is raised and the file object is not initialized.
Files can be opened and closed safely with a careful \li{try}-\li{except}-\li{else} control flow.

The keyword \li{with} can also be used in conjunction with an \li{open} statement to create an indented block in which the file is open.
Upon exiting the block, the file is closed safely and automatically.
This is the preferred method when a file only needs to be accessed briefly, but it is not quite as flexible as the \li{try}-\li{except}-\li{else} approach.

\begin{lstlisting}
>>> try:
...     myfile = open('in.txt', 'r')    # Open 'in.txt' with read-only access.
...     contents = myfile.readlines()   # Read in the content by line.
... except IOError as e:                # Check for errors.
...     print "File error:", e
... else:
...     myfile.close()                  # Explicitly close the file.

# Equivalently, use a 'with' statement to take care of errors.
>>> with open('in.txt', 'r') as myfile:     # Open 'in.txt' using 'with'.
...    contents = myfile.readlines()        # Read in the content by line.
...                                         # The file is closed automatically.
\end{lstlisting}

\subsection*{Reading and Writing}

\begin{table}
\begin{tabular}{|l|l|}
 \hline
Attribute & Description \\
\hline
\li{closed} & True if file object is closed. \\
\li{mode} & The access mode used to open the file object. \\
\li{name} & The name of the file. \\
\hline
\hline
Method & Description \\
\hline
\li{close()} & Flush any delayed writes and close the file object. \\
\li{read()} & Read the next string of the file (probably the whole file). \\
\li{readline()} & Read a line of the file, including the newline character at the end. \\
\li{readlines()} & Read lines of the file until the end of file (returned as a \li{list}). \\
\li{write()} & Write a string to the file. \\
\li{writelines()} & Write a sequence of strings to the file (input a \li{list}). Note that \\
 & newline characters are not added automatically.\\
\hline
\end{tabular}
\caption{Important \li{file} object attributes and methods.}
\label{table:fileattribs}
\end{table}

Every file object has several attributes and methods.
Some of the most notable are described in Table \ref{table:fileattribs}.
Only strings can be written to files; to write a non-string type, first cast it as a string using the \li{str} function.

\begin{lstlisting}
>>> try:
...     outfile = open('out.txt', 'w') # Open 'out.txt' with write-only access.
...     for i in xrange(10):
...         outfile.write(str(i**2))        # Write some strings to the file.
... except IOError as e:
...     print "Problem writing to file:", e
... else:
...     outfile.close()                     # Explicitly close the file.

# The flow is much less cumbersome using a 'with' statement.
>>> with open('out.txt', 'w') as outfile:   # Open 'out.txt' using 'with'.
...     for i in xrange(10):                
...         outfile.write(str(i**2))        # Write some strings to the file.
...
>>> outfile.closed                          # The file is closed automatically.
True
\end{lstlisting}

% Problem 4: Start the ContentFilter class.
\begin{problem}
Write a \li{ContentFilter} class.
The constructor should accept the name of a file to be read.
Store the name of the file and its contents as class attributes.
Remember to securely close the file.

If the filename argument is not a string, raise a \li{TypeError}.
\end{problem}

\subsection*{String Formatting}

% \begin{table}
% \begin{tabular}{|l|l|}
%  \hline
% Method & Returns \\
% \hline
% \li{isalpha()} & True if all characters in the string are alphabetic. \\
% \li{isdigit()} & True if all characters in the string are digits. \\
% \li{isspace()} & True if all characters in the string are whitespace (\li{" "}, \li{\\t}, \li{\\n}, etc). \\
% \li{capitalize()} & A copy of the string with only its first character capitalized. \\
% \li{lower()} & A copy of the string converted to lowercase. \\
% \li{upper()} & A copy of the string converted to uppercase. \\
% \li{split()} & A list of segments of the string, using a given character or string \\
%  & as a delimiter. The default is to separate on whitespace. \\
% \li{strip()} & A copy of the string with leading and trailing whitespace removed. \\
% \hline
% \end{tabular}
% \caption{Some of the important \li{str} object methods.}
% \label{table:strmethods}
% \end{table}

%A few of the more useful methods are listed in Table \ref{table:strmethods}.
%Talk about the is stuff (\li{isalnum}/\li{isspace}), formatting (\li{capitalize}/\li{lower}/\li{swapcase}), and \li{split} and \li{strip}.


Python's \li{str} class has several useful methods for formatting and arranging strings.
They are particularly useful for processing data from a source file.
As always, IPython's object introspection allows us to learn about these methods quickly.

\begin{lstlisting}
In [1]: str.    # Press 'tab'.
<<str.capitalize  str.isalnum     str.lstrip      str.splitlines
str.center      str.isalpha     str.partition   str.startswith
str.count       str.isdigit     str.replace     str.strip
str.decode      str.islower     str.rfind       str.swapcase
str.encode      str.isspace     str.rindex      str.title
str.endswith    str.istitle     str.rjust       str.translate
str.expandtabs  str.isupper     str.rpartition  str.upper
str.find        str.join        str.rsplit      str.zfill
str.format      str.ljust       str.rstrip      
str.index       str.lower       str.split>>

In [1]: str.upper?
Docstring:
S.upper() -> string

Return a copy of the string S converted to uppercase.
Type:      method_descriptor

In [2]: str.isupper?
<<Docstring:
S.isupper() -> bool

Return True if all cased characters in S are uppercase and there is
at least one cased character in S, False otherwise.
Type:      method_descriptor>>
\end{lstlisting}

Use IPython to learn about and get a feel for the following \li{str} methods: \li{isalpha()}, \li{isdigit()}, \li{isspace()}, \li{join()}, \li{lower()}, \li{replace()}, \li{split()}, \li{strip()}, and \li{upper()}.

Below, we demostrate the \li{join()} and \li{split()} methods.

\begin{lstlisting}
# str.join() puts the string between the entries of a list.
>>> words = ["state", "of", "the", "art"]
>>> "-".join(words)
'state-of-the-art'

# str.split() creates a list out of a string, given a delimiter.
>>> "One fish\nTwo fish\nRed fish\nBlue fish\n".split('\n')
['One fish', 'Two fish', 'Red fish', 'Blue fish', '']
\end{lstlisting}

% Problem 5: Add methods to the ContentFilter class.
\begin{problem}
Add the following methods to the \li{ContentFilter} class for writing the contents of the original file to new files.
Each method should accept a filename to write to and a keyword argument \li{mode} that specifies the file access mode, defaulting to \li{'w'}.
If \li{mode} is not either \li{'w'} or \li{'a'}, raise an \li{InvalidOptionError} with an informative message.

\begin{enumerate}

\item \li{hyphenate()}: write the data to the outfile in a single line, with \li{"-"} placed between each word and line.

\item \li{uniform()}: write the data to the outfile with uniform case. Include an additional keyword argument, \li{case}, that defaults to \li{'upper'}.

If \li{case='upper'}, write the data in upper case. If \li{case='lower'}, write the data in lower case. If \li{case} is not one of these two values, raise an \li{InvalidOptionError}.

\item \li{reverse()}: write the data to the outfile in reverse order. Include an additional keyword argument \li{unit} that defaults to \li{'line'}.

If \li{unit='word'}, reverse the ordering of the words in each line, but write the lines in the same order as the original file. If \li{unit='line'}, reverse the ordering of the lines, but do not change the ordering of the words on each individual line. If \li{unit} is not one of these two values, raise an \li{InvalidOptionError}.

\item \li{transpose()}: write a ``transposed'' version of the data to the outfile. That is, write the first word of each line of the data to the first line of the new file, the second word of each line of the data to the second line of the new file, and so on.
\end{enumerate}

Also implement the \li{__str__()} magic method so that printing a \li{ContentFilter} object yields the following output:
\begin{lstlisting}
<<Source file:              <filename>
Total characters:         <The total number of characters in the file>
Alphabetic characters:    <The number of letters>
Numerical characters:     <The number of digits>
Whitespace characters:    <The number of spaces, tabs, and newlines>
Number of lines:          <The number of lines>>>
\end{lstlisting}
\end{problem}

% These sections are incomplete. If desired, it needs some serious attention first.
\begin{comment}
\section*{Additional / Advanced Material}

\subsection*{The Finally Block}
Another optional block after a \li{try} block with the header \li{finally}.
The code in a \li{finally} block executes after either the try or any subsequent block completes, regardless of whether or not an exception was actually raised.
It is \textbf{always} executed, even if there is another exception raised in the \li{except} block or if a value is returned!

\begin{lstlisting}
>>> def finally_test(param):
...     try:
...         raise ValueError(str(param))
...     except ValueError as e:
...         return str(e)
...     finally:
...         print "This is a test."
...
>>> finally_test("input")
<<This is a test.
'input'>>
\end{lstlisting}

\subsection*{Function Wrappers}
A \emph{function wrapper} or \emph{decorator} is a function that is meant to ``wrap'' another function by being called on top of the target function.
That is, if we have a function $f$, wrapped by function $g$, then whenever $f$ is called, we actually are calling $f(g(x))$. % Or is it the other way around?

For example, let's create a wrapper that prints out the current time whenever the inner function is called.
\begin{lstlisting}
from time import strftime

def time_stamp(func):
    def wrapper(*args, **kwargs):
        print strftime("%H:%M:%S")
        return f(*args, **kwargs)
    return wrapper
\end{lstlisting}

\begin{lstlisting}
@time_stamp
def example():
    return 10

>>> example()
16:27:17
10
\end{lstlisting}

% Function decorator: timeout
\begin{problem}
Create a decorator that raises a \li{RuntimeError} after 10 seconds.
Consider using the \li{system} module.
\end{problem}
\end{comment}
